### ISSUE TITLE
Queries should have !closed by default

### ISSUE THREAD

**Issue by tonyandrewmeyer** [SpamExperts/trac-slack#4]
_(For discussion, since this may not be best)_

In our Trac, and I believe also a vanilla install, both the default logged in and logged out queries have `status=!closed`. I think this is sensible, as most of the time, especially on a well used Trac, you aren't interested in closed tickets. This means that you have to explicitly choose to include closed ones.

I think it would be useful to have this in the `/trac` query behaviour as well. i.e. "closed" (and synonyms) would need to be explicitly mentioned, and to get all tickets you would say something like "open and closed" (maybe "all" is a synonym for this?), and if you don't mention either, then you get only `!closed`.

Although this isn't as clean a match with the actual generated queries, I think it's more likely what people are expecting. Sometimes you want to see all the tickets (e.g. all tickets in the X milestone) but most of the time (e.g. all my bug tickets) you do not, and having to know/learn that you need to put "open" in there isn't as user friendly.

**Comment by alexkiro** [comment]
I think this makes sense and the logic should be something like:
- If no status can be extracted from the text the assume `!closed`
- If no status can be extracted from the text but the "all" keyword is present then show ALL tickets
- If a status can be extracted from the text don't assume the status and use the one provided by the user.
- If a status can be extracted from the text and the "all" keyword is present, still use the status provided by the user (e.g. `show all closed tickets`)

**Comment by alexkiro** [comment]
Done in 60c1e373a8f9b89581606c5cec4be85aaf3552bf and 94194630e1c17bef074a649fa0455c8ce1f69c20
